"""Data models package for FinPilot.

Structural foundation for domain schemas, request/response models,
and DB entities (Phase 2+).
"""

from app.models.context import (
    ContextChunk,
    ContextConfig,
    RetrievalContext,
)
from app.models.documents import (
    ChunkedDocument,
    ChunkMetadata,
    DocumentChunk,
    DocumentExtractionResult,
    DocumentType,
    DocumentUploadResponse,
    ExtractedPage,
    StoredDocument,
    ValidatedDocument,
    ValidatedPage,
)
from app.models.embeddings import (
    ChunkEmbeddingRequest,
    ChunkEmbeddingResult,
    DocumentEmbeddingBatch,
    EmbeddingModelInfo,
    QueryEmbeddingRequest,
    QueryEmbeddingResult,
)
from app.models.evidence import (
    ConflictingProvenanceError,
    EvidenceNotFoundError,
    EvidenceTrackingError,
    EvidenceValidationError,
    FabricatedProvenanceError,
    ResearchEvidence,
    compute_evidence_id,
)
from app.models.financial_data import (
    BalanceSheetPeriod,
    CashFlowPeriod,
    CompanyFundamentals,
    CompanyProfile,
    IncomeStatementPeriod,
    ProviderRawSnapshot,
)
from app.models.fundamental_metrics import (
    CashFlowMetrics,
    FundamentalMetrics,
    GrowthMetrics,
    LeverageMetrics,
    MetricSource,
    ProfitabilityMetrics,
    RevenueHistoryItem,
    ValuationMetrics,
)
from app.models.market_data import (
    HistoricalMarketData,
    OHLCVCandle,
)
from app.models.news import (
    NewsArticle,
    NewsSearchResult,
)
from app.models.news_processing import (
    ALLOWED_EVENT_TYPES,
    ALLOWED_SENTIMENTS,
    ArticleClassification,
    NewsEvent,
    NewsEventType,
    NewsProcessingBatchResult,
    ProcessedNewsArticle,
    SentimentType,
)
from app.models.relevance import (
    REASON_INSUFFICIENT_RELEVANT_CHUNKS,
    REASON_NO_EVIDENCE_WITHIN_THRESHOLD,
    REASON_NO_RETRIEVED_EVIDENCE,
    REASON_NOT_ALL_CHUNKS_RELEVANT,
    REASON_SUFFICIENT_EVIDENCE,
    RelevanceCheckResult,
    RelevanceConfig,
)
from app.models.retrieval import (
    TopKConfig,
    TopKRetrievalResult,
)
from app.models.technical_metrics import (
    MACDMetrics,
    MovingAverageMetrics,
    RSIMetrics,
    SupportResistanceMetrics,
    TechnicalMetrics,
    TechnicalScoreBreakdown,
    TrendDirection,
    VolumeMetrics,
)
from app.models.vector_store import (
    SimilaritySearchResults,
    VectorRecord,
    VectorSearchResult,
    VectorStoreInsertionResult,
)

__all__ = [
    "ALLOWED_EVENT_TYPES",
    "ALLOWED_SENTIMENTS",
    "ArticleClassification",
    "BalanceSheetPeriod",
    "CashFlowMetrics",
    "CashFlowPeriod",
    "ChunkEmbeddingRequest",
    "ChunkEmbeddingResult",
    "ChunkMetadata",
    "ChunkedDocument",
    "CompanyFundamentals",
    "CompanyProfile",
    "ConflictingProvenanceError",
    "ContextChunk",
    "ContextConfig",
    "compute_evidence_id",
    "DocumentChunk",
    "DocumentEmbeddingBatch",
    "DocumentExtractionResult",
    "DocumentType",
    "DocumentUploadResponse",
    "EmbeddingModelInfo",
    "EvidenceNotFoundError",
    "EvidenceTrackingError",
    "EvidenceValidationError",
    "ExtractedPage",
    "FabricatedProvenanceError",
    "FundamentalMetrics",
    "GrowthMetrics",
    "HistoricalMarketData",
    "IncomeStatementPeriod",
    "LeverageMetrics",
    "MACDMetrics",
    "MetricSource",
    "MovingAverageMetrics",
    "NewsArticle",
    "NewsEvent",
    "NewsEventType",
    "NewsProcessingBatchResult",
    "NewsSearchResult",
    "OHLCVCandle",
    "ProcessedNewsArticle",
    "ProfitabilityMetrics",
    "ProviderRawSnapshot",
    "QueryEmbeddingRequest",
    "QueryEmbeddingResult",
    "REASON_INSUFFICIENT_RELEVANT_CHUNKS",
    "REASON_NO_EVIDENCE_WITHIN_THRESHOLD",
    "REASON_NO_RETRIEVED_EVIDENCE",
    "REASON_NOT_ALL_CHUNKS_RELEVANT",
    "REASON_SUFFICIENT_EVIDENCE",
    "RelevanceCheckResult",
    "RelevanceConfig",
    "RSIMetrics",
    "ResearchEvidence",
    "RetrievalContext",
    "RevenueHistoryItem",
    "SentimentType",
    "SimilaritySearchResults",
    "StoredDocument",
    "SupportResistanceMetrics",
    "TechnicalMetrics",
    "TechnicalScoreBreakdown",
    "TopKConfig",
    "TopKRetrievalResult",
    "TrendDirection",
    "ValuationMetrics",
    "ValidatedDocument",
    "ValidatedPage",
    "VectorRecord",
    "VectorSearchResult",
    "VectorStoreInsertionResult",
    "VolumeMetrics",
]
