"""FinPilot Demo API - Streamlit-facing lightweight endpoints.

This router bypasses the full LangGraph multi-agent pipeline and routes
directly through Groq for demo / review purposes. Existing backend
files are untouched. This module stands completely alone.

Endpoints:
    POST /demo/clarify   - Given a raw user query, returns 1-2 smart
                           clarifying questions generated by Groq.
    POST /demo/analyze   - Given query + clarification answers, runs a
                           real multi-stage research pipeline (yfinance
                           market data + four specialist research passes)
                           and then synthesises a long-form structured
                           investment research report.

Model allocation
----------------
    Conversation Agent      -> groq/compound-mini   (higher TPM headroom)
    Technical Analyst       -> openai/gpt-oss-20b   + verified yfinance data
    Fundamental Analyst     -> openai/gpt-oss-20b   + verified yfinance data
    News & Sentiment Agent  -> openai/gpt-oss-20b   + yfinance headlines
    Risk Assessment Agent   -> openai/gpt-oss-20b   + verified yfinance data
    Final Synthesis         -> groq/compound-mini   (heaviest context/report)

Research policy
---------------
All quantitative facts (price, moving averages, RSI, MACD, volatility,
valuation ratios, margins, debt) come from yfinance, never from model
memory. The specialist agents interpret that verified block only.
Anything that cannot be sourced is reported as explicitly unavailable.
"""

import asyncio
import json
import os
import re
import statistics
from datetime import datetime, timezone
from typing import Any, Dict, List, Optional, Tuple

from fastapi import APIRouter, HTTPException, status
from pydantic import BaseModel, Field

# ---------------------------------------------------------------------------
# Groq client bootstrap
# ---------------------------------------------------------------------------
try:
    from groq import Groq
    _GROQ_AVAILABLE = True
except ImportError:
    _GROQ_AVAILABLE = False

# ---------------------------------------------------------------------------
# Market data provider (graceful degradation if absent)
# ---------------------------------------------------------------------------
try:
    import yfinance as yf
    _YF_AVAILABLE = True
except Exception:  # pragma: no cover - import guard only
    _YF_AVAILABLE = False

router = APIRouter()


# --- Model allocation -------------------------------------------------------
# Specialist analysts: fast, cheap, no tool orchestration required.
SPECIALIST_MODEL = os.getenv("LLM_MODEL", "openai/gpt-oss-20b")
# Conversation + final synthesis: larger context / TPM allowance.
ORCHESTRATOR_MODEL = os.getenv("SYNTHESIS_MODEL", "groq/compound-mini")

# --- Token budgets (kept within Groq per-minute limits) ---------------------
CLARIFY_TOKENS = 512
RESOLVE_TOKENS = 200
PROFILE_TOKENS = 900
TECHNICAL_TOKENS = 1400
FUNDAMENTAL_TOKENS = 1500
NEWS_TOKENS = 1300
RISK_TOKENS = 1500
SYNTHESIS_TOKENS = int(os.getenv("SYNTHESIS_MAX_TOKENS", "6500"))


_NO_FABRICATION_RULE = (
    "STRICT SOURCING RULES:\n"
    "- Use ONLY the verified data block supplied to you.\n"
    "- NEVER invent prices, indicator values, ratios, revenue figures, analyst "
    "targets, ratings, price targets or news events.\n"
    "- You have no live browsing. If a number or fact is not in the verified "
    "block, write that it is unavailable, then reason qualitatively.\n"
    "- Distinguish clearly between measured data and your own interpretation.\n"
    "- Never state or imply a guaranteed return."
)


def _get_groq_client():
    """Return a configured Groq client or raise 503."""
    if not _GROQ_AVAILABLE:
        raise HTTPException(
            status_code=status.HTTP_503_SERVICE_UNAVAILABLE,
            detail="groq package is not installed.",
        )

    api_key = os.getenv("GROQ_API_KEY", "")

    if not api_key:
        raise HTTPException(
            status_code=status.HTTP_503_SERVICE_UNAVAILABLE,
            detail="GROQ_API_KEY is not configured in environment.",
        )

    return Groq(api_key=api_key)


def _generate_text(
    prompt: str,
    system: str = "",
    max_tokens: int = 2048,
    temperature: float = 0.4,
    model: Optional[str] = None,
) -> str:
    """Call a Groq model and return plain text response.

    Falls back to the same call without ``temperature`` if the target model
    rejects that parameter, then to the specialist model if the requested
    model is unavailable on this account.
    """

    client = _get_groq_client()
    model = model or SPECIALIST_MODEL

    messages: List[Dict[str, str]] = []
    if system:
        messages.append({"role": "system", "content": system})
    messages.append({"role": "user", "content": prompt})

    attempts: List[Dict[str, Any]] = [
        {
            "model": model,
            "messages": messages,
            "temperature": temperature,
            "max_tokens": max_tokens,
        },
        {
            "model": model,
            "messages": messages,
            "max_tokens": max_tokens,
        },
    ]
    if model != SPECIALIST_MODEL:
        attempts.append({
            "model": SPECIALIST_MODEL,
            "messages": messages,
            "temperature": temperature,
            "max_tokens": max_tokens,
        })

    last_error: Optional[Exception] = None
    for kwargs in attempts:
        try:
            response = client.chat.completions.create(**kwargs)
            text = response.choices[0].message.content or ""
            if text.strip():
                return text
        except Exception as exc:  # try the next fallback shape
            last_error = exc
            continue

    if last_error:
        raise last_error
    return ""


# ---------------------------------------------------------------------------
# Indicator helpers (computed from real price history, never guessed)
# ---------------------------------------------------------------------------

def _sma(values: List[float], window: int) -> Optional[float]:
    if len(values) < window:
        return None
    return sum(values[-window:]) / window


def _ema_series(values: List[float], window: int) -> List[float]:
    if not values:
        return []
    k = 2.0 / (window + 1.0)
    out = [values[0]]
    for v in values[1:]:
        out.append(v * k + out[-1] * (1 - k))
    return out


def _rsi(values: List[float], period: int = 14) -> Optional[float]:
    if len(values) < period + 1:
        return None
    gains, losses = [], []
    for prev, cur in zip(values[-(period + 1):-1], values[-period:]):
        change = cur - prev
        gains.append(max(change, 0.0))
        losses.append(max(-change, 0.0))
    avg_gain = sum(gains) / period
    avg_loss = sum(losses) / period
    if avg_loss == 0:
        return 100.0
    rs = avg_gain / avg_loss
    return 100.0 - (100.0 / (1.0 + rs))


def _macd(
    values: List[float],
) -> Tuple[Optional[float], Optional[float], Optional[float]]:
    if len(values) < 35:
        return None, None, None
    ema12 = _ema_series(values, 12)
    ema26 = _ema_series(values, 26)
    macd_line = [a - b for a, b in zip(ema12[-len(ema26):], ema26)]
    signal = _ema_series(macd_line, 9)
    return macd_line[-1], signal[-1], macd_line[-1] - signal[-1]


def _annualised_volatility(values: List[float]) -> Optional[float]:
    if len(values) < 30:
        return None
    rets = [
        (b - a) / a
        for a, b in zip(values[:-1], values[1:])
        if a
    ]
    if len(rets) < 20:
        return None
    return statistics.pstdev(rets[-252:]) * (252 ** 0.5) * 100.0


def _num(value: Any) -> Optional[float]:
    try:
        if value is None:
            return None
        f = float(value)
        if f != f:  # NaN
            return None
        return f
    except (TypeError, ValueError):
        return None


def _fmt(value: Optional[float], suffix: str = "", digits: int = 2) -> str:
    if value is None:
        return "unavailable"
    return f"{value:,.{digits}f}{suffix}"


def _fmt_big(value: Optional[float]) -> str:
    if value is None:
        return "unavailable"
    for cutoff, unit in ((1e12, "T"), (1e9, "B"), (1e6, "M")):
        if abs(value) >= cutoff:
            return f"{value / cutoff:,.2f}{unit}"
    return f"{value:,.0f}"


# ---------------------------------------------------------------------------
# Market data collection (yfinance = the single factual layer)
# ---------------------------------------------------------------------------

def _fetch_market_data(ticker: str) -> Dict[str, Any]:
    """Pull real price history, indicators, fundamentals and headlines.

    Never raises: any failure is recorded in ``notes`` so downstream
    prompts can honestly declare the gap.
    """

    data: Dict[str, Any] = {
        "ticker": ticker,
        "price_available": False,
        "fundamentals_available": False,
        "headlines": [],
        "notes": [],
        "as_of": datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M UTC"),
    }

    if not ticker or ticker == "N/A":
        data["notes"].append("No ticker symbol could be resolved from the query.")
        return data

    if not _YF_AVAILABLE:
        data["notes"].append(
            "Market data provider (yfinance) is not installed on this server, "
            "so live prices and computed indicators are unavailable."
        )
        return data

    try:
        handle = yf.Ticker(ticker)
    except Exception as exc:
        data["notes"].append(f"Could not open market data handle: {exc}")
        return data

    # --- price history + indicators -------------------------------------
    try:
        hist = handle.history(period="1y", interval="1d")
        closes = [float(c) for c in hist["Close"].dropna().tolist()]
        volumes = [float(v) for v in hist["Volume"].dropna().tolist()]

        if len(closes) >= 30:
            macd_line, macd_signal, macd_hist = _macd(closes)
            data.update({
                "price_available": True,
                "bars": len(closes),
                "last_close": closes[-1],
                "prev_close": closes[-2] if len(closes) > 1 else None,
                "change_pct": (
                    (closes[-1] - closes[-2]) / closes[-2] * 100.0
                    if len(closes) > 1 and closes[-2] else None
                ),
                "period_high": max(closes),
                "period_low": min(closes),
                "pct_from_high": (max(closes) - closes[-1]) / max(closes) * 100.0,
                "pct_from_low": (closes[-1] - min(closes)) / min(closes) * 100.0,
                "return_1y_pct": (closes[-1] - closes[0]) / closes[0] * 100.0,
                "sma20": _sma(closes, 20),
                "sma50": _sma(closes, 50),
                "sma200": _sma(closes, 200),
                "rsi14": _rsi(closes, 14),
                "macd": macd_line,
                "macd_signal": macd_signal,
                "macd_hist": macd_hist,
                "volatility_pct": _annualised_volatility(closes),
                "avg_volume_30d": (
                    sum(volumes[-30:]) / len(volumes[-30:]) if volumes else None
                ),
            })
        else:
            data["notes"].append(
                "Insufficient daily price history returned to compute indicators."
            )
    except Exception as exc:
        data["notes"].append(f"Price history unavailable: {exc}")

    # --- fundamentals ----------------------------------------------------
    try:
        info: Dict[str, Any] = {}
        try:
            info = handle.get_info() or {}
        except Exception:
            info = getattr(handle, "info", {}) or {}

        if info:
            data.update({
                "fundamentals_available": True,
                "long_name": info.get("longName") or info.get("shortName"),
                "sector": info.get("sector"),
                "industry": info.get("industry"),
                "currency": info.get("currency"),
                "exchange": info.get("fullExchangeName") or info.get("exchange"),
                "market_cap": _num(info.get("marketCap")),
                "trailing_pe": _num(info.get("trailingPE")),
                "forward_pe": _num(info.get("forwardPE")),
                "price_to_book": _num(info.get("priceToBook")),
                "peg_ratio": _num(info.get("pegRatio")),
                "profit_margin": _num(info.get("profitMargins")),
                "operating_margin": _num(info.get("operatingMargins")),
                "revenue_growth": _num(info.get("revenueGrowth")),
                "earnings_growth": _num(info.get("earningsGrowth")),
                "return_on_equity": _num(info.get("returnOnEquity")),
                "debt_to_equity": _num(info.get("debtToEquity")),
                "current_ratio": _num(info.get("currentRatio")),
                "total_revenue": _num(info.get("totalRevenue")),
                "free_cash_flow": _num(info.get("freeCashflow")),
                "dividend_yield": _num(info.get("dividendYield")),
                "beta": _num(info.get("beta")),
                "business_summary": (info.get("longBusinessSummary") or "")[:1200],
            })
        else:
            data["notes"].append("Company fundamentals could not be retrieved.")
    except Exception as exc:
        data["notes"].append(f"Fundamentals unavailable: {exc}")

    # --- recent headlines (real, provider supplied) -----------------------
    try:
        raw_news = getattr(handle, "news", None) or []
        for item in raw_news[:10]:
            content = item.get("content") if isinstance(item, dict) else None
            if isinstance(content, dict):
                title = content.get("title")
                publisher = (content.get("provider") or {}).get("displayName")
                published = content.get("pubDate")
            else:
                title = item.get("title")
                publisher = item.get("publisher")
                ts = item.get("providerPublishTime")
                published = (
                    datetime.fromtimestamp(ts, timezone.utc).strftime("%Y-%m-%d")
                    if ts else None
                )
            if title:
                data["headlines"].append({
                    "title": title,
                    "publisher": publisher or "unknown publisher",
                    "published": published or "date unavailable",
                })
        if not data["headlines"]:
            data["notes"].append("No provider headlines returned for this ticker.")
    except Exception as exc:
        data["notes"].append(f"Headline feed unavailable: {exc}")

    return data


def _format_price_facts(md: Dict[str, Any]) -> str:
    if not md.get("price_available"):
        return (
            "VERIFIED PRICE DATA: UNAVAILABLE.\n"
            + "\n".join(f"- {n}" for n in md.get("notes", []))
        )

    cur = md.get("currency") or ""
    return "\n".join([
        (
            f"VERIFIED MARKET DATA (yfinance; computed from "
            f"{md.get('bars')} daily bars, as of {md['as_of']}):"
        ),
        f"- Ticker: {md['ticker']} ({md.get('exchange') or 'exchange unavailable'})",
        f"- Last close: {_fmt(md.get('last_close'))} {cur}",
        f"- Session change: {_fmt(md.get('change_pct'), '%')}",
        f"- Trailing 12m return: {_fmt(md.get('return_1y_pct'), '%')}",
        (
            f"- 52w-window high / low: "
            f"{_fmt(md.get('period_high'))} / {_fmt(md.get('period_low'))}"
        ),
        f"- Distance below window high: {_fmt(md.get('pct_from_high'), '%')}",
        f"- Distance above window low: {_fmt(md.get('pct_from_low'), '%')}",
        (
            f"- SMA20 / SMA50 / SMA200: "
            f"{_fmt(md.get('sma20'))} / {_fmt(md.get('sma50'))} / "
            f"{_fmt(md.get('sma200'))}"
        ),
        f"- RSI(14): {_fmt(md.get('rsi14'))}",
        (
            f"- MACD line / signal / histogram: "
            f"{_fmt(md.get('macd'), digits=4)} / "
            f"{_fmt(md.get('macd_signal'), digits=4)} / "
            f"{_fmt(md.get('macd_hist'), digits=4)}"
        ),
        f"- Annualised realised volatility: {_fmt(md.get('volatility_pct'), '%')}",
        f"- Average 30d volume: {_fmt_big(md.get('avg_volume_30d'))}",
    ])


def _format_fundamental_facts(md: Dict[str, Any]) -> str:
    if not md.get("fundamentals_available"):
        return "VERIFIED FUNDAMENTAL DATA: UNAVAILABLE for this ticker."

    def pct(v: Optional[float]) -> str:
        return "unavailable" if v is None else f"{v * 100:,.2f}%"

    return "\n".join([
        "VERIFIED FUNDAMENTAL DATA (yfinance):",
        f"- Company: {md.get('long_name') or 'unavailable'}",
        (
            f"- Sector / industry: {md.get('sector') or 'unavailable'} / "
            f"{md.get('industry') or 'unavailable'}"
        ),
        (
            f"- Market capitalisation: {_fmt_big(md.get('market_cap'))} "
            f"{md.get('currency') or ''}"
        ),
        (
            f"- Trailing P/E: {_fmt(md.get('trailing_pe'))} | "
            f"Forward P/E: {_fmt(md.get('forward_pe'))}"
        ),
        (
            f"- Price/Book: {_fmt(md.get('price_to_book'))} | "
            f"PEG: {_fmt(md.get('peg_ratio'))}"
        ),
        (
            f"- Revenue (TTM): {_fmt_big(md.get('total_revenue'))} | "
            f"Free cash flow: {_fmt_big(md.get('free_cash_flow'))}"
        ),
        (
            f"- Revenue growth: {pct(md.get('revenue_growth'))} | "
            f"Earnings growth: {pct(md.get('earnings_growth'))}"
        ),
        (
            f"- Operating margin: {pct(md.get('operating_margin'))} | "
            f"Net margin: {pct(md.get('profit_margin'))}"
        ),
        f"- Return on equity: {pct(md.get('return_on_equity'))}",
        (
            f"- Debt/Equity: {_fmt(md.get('debt_to_equity'))} | "
            f"Current ratio: {_fmt(md.get('current_ratio'))}"
        ),
        (
            f"- Dividend yield: {pct(md.get('dividend_yield'))} | "
            f"Beta: {_fmt(md.get('beta'))}"
        ),
        (
            f"- Business description (provider supplied): "
            f"{md.get('business_summary') or 'unavailable'}"
        ),
    ])


def _format_headlines(md: Dict[str, Any]) -> str:
    if not md.get("headlines"):
        return (
            "PROVIDER HEADLINES: none returned. Treat recent news flow and "
            "analyst positioning as unavailable."
        )
    lines = ["PROVIDER HEADLINES (real, retrieved from the market data provider):"]
    for h in md["headlines"]:
        lines.append(f"- [{h['published']}] {h['title']} ({h['publisher']})")
    return "\n".join(lines)


def _collect_sources(md: Dict[str, Any]) -> List[str]:
    """Report only the data sources actually used."""
    sources: List[str] = []
    if md.get("price_available") or md.get("fundamentals_available"):
        sources.append("Yahoo Finance market data (via yfinance)")
    publishers = sorted({
        h.get("publisher", "").strip()
        for h in md.get("headlines", [])
        if h.get("publisher")
    })
    sources.extend(publishers)
    if not sources:
        sources.append("No external data source was reachable for this analysis.")
    return sources


# ---------------------------------------------------------------------------
# Pydantic Models
# ---------------------------------------------------------------------------

class ClarifyRequest(BaseModel):
    query: str = Field(..., description="Raw user query about a company or stock.")


class ClarifyResponse(BaseModel):
    questions: List[str]
    detected_ticker: Optional[str] = None
    detected_company: Optional[str] = None


class AnalyzeRequest(BaseModel):
    query: str = Field(..., description="Original user query.")
    clarification_answers: Optional[Dict[str, str]] = Field(
        default=None,
        description="Map of question text to user answer.",
    )
    ticker: Optional[str] = None
    target_company: Optional[str] = None


class AgentStatus(BaseModel):
    name: str
    status: str
    summary: str


class AnalyzeResponse(BaseModel):
    ticker: str
    company: str
    executive_summary: str
    technical_outlook: str
    fundamental_view: str
    news_sentiment: str
    risk_assessment: str
    final_verdict: str
    confidence: str
    disclaimer: str
    agent_statuses: List[AgentStatus]
    raw_markdown: str

    # --- optional enrichment (defaults keep the Streamlit payload compatible)
    investor_profile: str = ""
    valuation_view: str = ""
    scenario_analysis: str = ""
    catalysts_to_watch: str = ""
    data_availability: str = ""
    key_metrics: Dict[str, str] = Field(default_factory=dict)
    sources: List[str] = Field(default_factory=list)
    research_briefs: Dict[str, str] = Field(default_factory=dict)


# ---------------------------------------------------------------------------
# Clarification Endpoint  (behaviour preserved exactly)
# ---------------------------------------------------------------------------

_CLARIFY_SYSTEM = """You are FinPilot's Clarification Agent.
Read the user's financial query and generate exactly 1 or 2 smart, concise
clarifying questions that will help produce a better investment analysis.

Rules:
- Only ask what is genuinely missing from the query.
- If investment horizon is not mentioned, ask it.
- If risk tolerance is not mentioned, ask it.
- If the query is already very specific, ask only 1 question.
- Do NOT ask about the company/ticker if already mentioned.
- Keep questions short (under 15 words each).
- Respond ONLY as a valid JSON object, no extra text:
  {
    "questions": ["Question 1?", "Question 2?"],
    "detected_ticker": "AAPL",
    "detected_company": "Apple Inc."
  }
- detected_ticker and detected_company should be null if not found in the query.
"""


@router.post(
    "/clarify",
    response_model=ClarifyResponse,
    summary="Generate clarifying questions for a user query",
    description=(
        "Sends the raw user query to Groq and returns 1-2 targeted "
        "clarifying questions to sharpen the investment analysis."
    ),
    operation_id="demoClarifyQuery",
)
async def clarify_query(request: ClarifyRequest) -> ClarifyResponse:
    """Generate clarifying questions from Groq for the given query."""
    prompt = f"User Query: {request.query}"
    try:
        raw = _generate_text(
            prompt=prompt,
            system=_CLARIFY_SYSTEM,
            max_tokens=CLARIFY_TOKENS,
            model=SPECIALIST_MODEL,
        )
    except HTTPException:
        raise
    except Exception as exc:
        raise HTTPException(
            status_code=status.HTTP_500_INTERNAL_SERVER_ERROR,
            detail=f"Groq clarification call failed: {exc}",
        ) from exc

    # Strip markdown fences if Groq wraps in ```json
    cleaned = re.sub(r"```(?:json)?", "", raw).strip().strip("`").strip()
    try:
        parsed: Dict[str, Any] = json.loads(cleaned)
    except json.JSONDecodeError:
        # Fallback: pull out anything that looks like a question
        qs = re.findall(r'"([^"]+\?)"', cleaned)
        parsed = {
            "questions": qs[:2] if qs else ["What is your investment horizon?"],
            "detected_ticker": None,
            "detected_company": None,
        }

    return ClarifyResponse(
        questions=parsed.get("questions", ["What is your investment horizon?"])[:2],
        detected_ticker=parsed.get("detected_ticker"),
        detected_company=parsed.get("detected_company"),
    )


# ---------------------------------------------------------------------------
# Research pipeline helpers
# ---------------------------------------------------------------------------

_RESOLVE_SYSTEM = """You map a financial query to a listed instrument.
Respond ONLY with JSON, no prose:
{"ticker": "EXCHANGE-CORRECT SYMBOL", "company": "Full legal name"}
Rules:
- Use the exact symbol used by Yahoo Finance (e.g. AAPL, MSFT, TSLA,
  RELIANCE.NS, TCS.NS, INFY.NS, 7203.T, SAP.DE).
- Indian NSE listings must end in .NS, BSE listings in .BO.
- If the query names no identifiable listed company, return
  {"ticker": null, "company": null}. Do not guess a random company.
"""


def _resolve_instrument(
    query: str,
    ticker: Optional[str],
    company: Optional[str],
) -> Tuple[str, str, List[str]]:
    """Resolve and validate the ticker. Returns (ticker, company, notes)."""
    notes: List[str] = []

    if ticker:
        return ticker.strip().upper(), (company or "").strip(), notes

    try:
        raw = _generate_text(
            prompt=f"Query: {query}\nCompany hint: {company or 'none'}",
            system=_RESOLVE_SYSTEM,
            max_tokens=RESOLVE_TOKENS,
            temperature=0.0,
            model=SPECIALIST_MODEL,
        )
        cleaned = re.sub(r"```(?:json)?", "", raw).strip().strip("`").strip()
        parsed = json.loads(cleaned)
        resolved_ticker = (parsed.get("ticker") or "").strip().upper()
        resolved_company = (parsed.get("company") or "").strip()
    except Exception as exc:
        notes.append(f"Ticker resolution failed ({exc}); analysis will be qualitative.")
        return "N/A", (company or "Unknown Company"), notes

    if not resolved_ticker:
        notes.append(
            "No listed instrument could be identified from the query, so no "
            "market data was retrieved."
        )
        return "N/A", (resolved_company or company or "Unknown Company"), notes

    return resolved_ticker, (resolved_company or company or ""), notes


def _profile_text(request: AnalyzeRequest) -> str:
    parts = [f"User Query: {request.query}"]
    if request.clarification_answers:
        parts.append("Clarification answers:")
        for q, a in request.clarification_answers.items():
            parts.append(f"  - {q}: {a}")
    else:
        parts.append("Clarification answers: none provided (user skipped).")
    return "\n".join(parts)


# --- individual research stages (each runs in its own thread) ---------------

def _stage_profile(request: AnalyzeRequest, md: Dict[str, Any]) -> Dict[str, str]:
    """Conversation Agent — runs on Compound Mini."""
    system = (
        "You are FinPilot's Conversation Agent. Convert the user's query and "
        "clarification answers into a precise investor mandate.\n"
        "Cover: objective, investment horizon, risk tolerance, likely position "
        "sizing context, constraints, and what the downstream analysis must "
        "therefore prioritise. If the user did not state horizon or risk "
        "tolerance, say so explicitly and state the neutral default you assume. "
        "Do not analyse the stock and do not introduce any market figures. "
        "200-300 words, prose."
    )
    text = _generate_text(
        prompt=_profile_text(request),
        system=system,
        max_tokens=PROFILE_TOKENS,
        temperature=0.3,
        model=ORCHESTRATOR_MODEL,
    )
    return {
        "name": "Conversation Agent",
        "status": "completed",
        "summary": (
            "Investor mandate assembled from "
            f"{len(request.clarification_answers or {})} clarification answer(s)."
        ),
        "brief": text,
    }


def _stage_technical(request: AnalyzeRequest, md: Dict[str, Any]) -> Dict[str, str]:
    """Technical Analyst — GPT-OSS 20B over verified yfinance indicators."""
    system = (
        "You are FinPilot's Technical Analyst.\n" + _NO_FABRICATION_RULE + "\n"
        "Interpret ONLY the supplied indicator values. Cover: primary trend "
        "(price vs SMA20/50/200 and their alignment), momentum (RSI and MACD "
        "histogram), position within the 52-week range, realised volatility and "
        "what it implies for position sizing, observable support/resistance "
        "anchored to the supplied levels only, and volume context. State clearly "
        "which readings are constructive and which are cautionary. "
        "400-550 words, prose."
    )
    prompt = "\n\n".join([
        _profile_text(request),
        _format_price_facts(md),
    ])
    text = _generate_text(
        prompt=prompt,
        system=system,
        max_tokens=TECHNICAL_TOKENS,
        temperature=0.3,
        model=SPECIALIST_MODEL,
    )

    if md.get("price_available"):
        summary = (
            f"{md.get('bars')} daily bars analysed; RSI(14) {_fmt(md.get('rsi14'))}, "
            f"last close {_fmt(md.get('last_close'))}."
        )
        stage_status = "completed"
    else:
        summary = "Live price history unavailable; qualitative trend framing only."
        stage_status = "partial"

    return {
        "name": "Technical Analyst",
        "status": stage_status,
        "summary": summary,
        "brief": text,
    }


def _stage_fundamental(request: AnalyzeRequest, md: Dict[str, Any]) -> Dict[str, str]:
    """Fundamental Analyst — GPT-OSS 20B over verified yfinance fundamentals."""
    system = (
        "You are FinPilot's Fundamental Analyst.\n" + _NO_FABRICATION_RULE + "\n"
        "Cover: business model and revenue mix (from the supplied description "
        "only), growth trajectory, margin structure, returns on capital, balance "
        "sheet strength and leverage, cash generation, what the supplied "
        "valuation multiples imply, and the durability of the competitive moat. "
        "Any ratio not present in the block must be called unavailable rather "
        "than estimated. Quote the supplied figures when you reason about them. "
        "500-650 words, prose."
    )
    prompt = "\n\n".join([
        _profile_text(request),
        f"Ticker under review: {md.get('ticker')}",
        _format_fundamental_facts(md),
        _format_price_facts(md),
    ])
    text = _generate_text(
        prompt=prompt,
        system=system,
        max_tokens=FUNDAMENTAL_TOKENS,
        temperature=0.3,
        model=SPECIALIST_MODEL,
    )

    if md.get("fundamentals_available"):
        summary = (
            f"Valuation and statement metrics analysed "
            f"(P/E {_fmt(md.get('trailing_pe'))}, "
            f"market cap {_fmt_big(md.get('market_cap'))})."
        )
        stage_status = "completed"
    else:
        summary = "Structured fundamentals unavailable; qualitative view only."
        stage_status = "partial"

    return {
        "name": "Fundamental Analyst",
        "status": stage_status,
        "summary": summary,
        "brief": text,
    }


def _stage_news(request: AnalyzeRequest, md: Dict[str, Any]) -> Dict[str, str]:
    """News & Sentiment Agent — GPT-OSS 20B over yfinance provider headlines."""
    system = (
        "You are FinPilot's News & Sentiment Agent.\n" + _NO_FABRICATION_RULE + "\n"
        "Work ONLY from the supplied headlines. Cover: the dominant narrative of "
        "the coverage, the concrete themes and catalysts the headlines point to, "
        "any regulatory or legal angle visible in them, how the coverage lines up "
        "with the price action in the verified block, and the overall tone "
        "(constructive / mixed / negative) with the specific headlines that "
        "justify that call. Do NOT invent analyst ratings, price targets or "
        "events that are not in the headline list; if none were supplied, state "
        "plainly that recent news flow and analyst positioning are unavailable "
        "and keep this section short and honest. 350-550 words, prose."
    )
    prompt = "\n\n".join([
        _profile_text(request),
        (
            f"Ticker under review: {md.get('ticker')} "
            f"({md.get('long_name') or 'name unavailable'})"
        ),
        _format_headlines(md),
        _format_price_facts(md),
    ])
    text = _generate_text(
        prompt=prompt,
        system=system,
        max_tokens=NEWS_TOKENS,
        temperature=0.3,
        model=SPECIALIST_MODEL,
    )

    headline_count = len(md.get("headlines", []))
    return {
        "name": "News & Sentiment Agent",
        "status": "completed" if headline_count else "partial",
        "summary": (
            f"{headline_count} provider headline(s) reviewed."
            if headline_count
            else "No headlines returned; news flow reported as unavailable."
        ),
        "brief": text,
    }


def _stage_risk(request: AnalyzeRequest, md: Dict[str, Any]) -> Dict[str, str]:
    """Risk Assessment Agent — GPT-OSS 20B over verified yfinance data."""
    system = (
        "You are FinPilot's Risk Assessment Agent.\n" + _NO_FABRICATION_RULE + "\n"
        "Produce a structured risk register covering: market/beta risk, sector and "
        "cyclicality risk, company-specific operating and balance-sheet risk, "
        "valuation risk, liquidity risk, macro and rate sensitivity, and "
        "regulatory/geopolitical exposure. For each, state the evidence from the "
        "verified block (or that the evidence is unavailable), a qualitative "
        "severity (low/medium/high) and a practical mitigation. Close with the "
        "risks most relevant to this specific investor mandate. "
        "500-650 words, prose with clear labels."
    )
    prompt = "\n\n".join([
        _profile_text(request),
        _format_price_facts(md),
        _format_fundamental_facts(md),
    ])
    text = _generate_text(
        prompt=prompt,
        system=system,
        max_tokens=RISK_TOKENS,
        temperature=0.3,
        model=SPECIALIST_MODEL,
    )

    return {
        "name": "Risk Assessment Agent",
        "status": "completed",
        "summary": (
            "Risk register built across market, sector, company, valuation and "
            f"macro factors (beta {_fmt(md.get('beta'))}, realised vol "
            f"{_fmt(md.get('volatility_pct'), '%')})."
        ),
        "brief": text,
    }


async def _run_research(
    request: AnalyzeRequest, md: Dict[str, Any]
) -> List[Dict[str, str]]:
    """Run the five research stages concurrently, tolerating individual failures."""

    stages = [
        ("Conversation Agent", _stage_profile),
        ("Technical Analyst", _stage_technical),
        ("Fundamental Analyst", _stage_fundamental),
        ("News & Sentiment Agent", _stage_news),
        ("Risk Assessment Agent", _stage_risk),
    ]

    results = await asyncio.gather(
        *(asyncio.to_thread(fn, request, md) for _, fn in stages),
        return_exceptions=True,
    )

    output: List[Dict[str, str]] = []
    for (name, _), result in zip(stages, results):
        if isinstance(result, Exception):
            output.append({
                "name": name,
                "status": "failed",
                "summary": f"Stage could not complete: {result}",
                "brief": (
                    f"{name} produced no output; "
                    "treat this dimension as unresearched."
                ),
            })
        else:
            output.append(result)
    return output


# ---------------------------------------------------------------------------
# Synthesis  (Compound Mini)
# ---------------------------------------------------------------------------

_ANALYSIS_SYSTEM = """You are FinPilot's Chief Investment Strategist.

Five specialist research briefs, a verified market-data block, verified
fundamentals, provider headlines and a list of data gaps have been prepared for
you. Your job is SYNTHESIS: weigh the evidence, resolve tensions between the
briefs, and produce a long-form institutional-grade research note.

""" + _NO_FABRICATION_RULE + """

Additional requirements:
- Every quantitative claim must trace back to the verified data block or to a
  brief that referenced it. Do not introduce any fact, figure, event, rating or
  price target that is not present in the supplied material, and do not rely on
  outside recall.
- If something was flagged unavailable, carry that caveat forward instead of
  filling the gap.
- Where the briefs disagree, say so explicitly and explain which evidence you
  weight more heavily and why.
- Be analytical, not descriptive: explain what each fact implies for the stated
  investor mandate.
- Give no buy/sell/hold rating. Frame conclusions as considerations.

Respond ONLY with a valid JSON object - no markdown fences, no extra text:
{
  "ticker": "TICKER",
  "company": "Full Company Name",
  "investor_profile": "150-200 words restating the mandate the analysis serves.",
  "executive_summary": "250-350 words. The complete thesis, the two or three
     facts that drive it, and the principal uncertainty.",
  "technical_outlook": "400-550 words citing the verified indicator values.",
  "fundamental_view": "450-600 words on growth, margins, returns, balance sheet
     and moat.",
  "valuation_view": "250-350 words on what the supplied multiples imply and what
     has to be true to justify them.",
  "news_sentiment": "300-450 words grounded strictly in the supplied headlines;
     if none were supplied, say so and keep it brief.",
  "risk_assessment": "450-600 words as a labelled risk register with severities.",
  "scenario_analysis": "250-350 words: base, bull and bear cases described
     qualitatively with the conditions that would confirm each. No price targets.",
  "catalysts_to_watch": "150-250 words listing expected events and the metrics
     that would change the thesis.",
  "final_verdict": "250-350 words tying everything back to the investor's stated
     horizon and risk tolerance. Balanced. No rating.",
  "confidence": "High or Medium or Low",
  "data_availability": "80-150 words stating exactly which data was live and
     verified, and which was unavailable at analysis time.",
  "key_metrics": {"Metric name": "value exactly as supplied, or 'unavailable'"},
  "sources": ["data source actually used", "..."],
  "disclaimer": "One-sentence standard investment disclaimer."
}

confidence = High only when verified price AND fundamental data were both
present and the briefs agree; Medium when data is partial; Low when the
instrument could not be resolved or most data was unavailable.
"""


def _build_synthesis_prompt(
    request: AnalyzeRequest,
    md: Dict[str, Any],
    briefs: List[Dict[str, str]],
    resolution_notes: List[str],
) -> str:
    parts = [
        "=== INVESTOR INPUT ===",
        _profile_text(request),
        "",
        f"Resolved instrument: {md.get('ticker')} / "
        f"{md.get('long_name') or request.target_company or 'name unavailable'}",
        "",
        "=== VERIFIED DATA ===",
        _format_price_facts(md),
        "",
        _format_fundamental_facts(md),
        "",
        _format_headlines(md),
        "",
        "=== DATA GAPS RECORDED DURING COLLECTION ===",
    ]
    gaps = list(md.get("notes", [])) + list(resolution_notes)
    parts.append(
        "\n".join(f"- {g}" for g in gaps)
        if gaps else "- None; all requested data was retrieved."
    )

    parts.append("\n=== SPECIALIST RESEARCH BRIEFS ===")
    for b in briefs:
        parts.append(f"\n--- {b['name']} (status: {b['status']}) ---\n{b['brief']}")

    parts.append("\n=== DATA SOURCES ACTUALLY USED ===")
    parts.append("\n".join(f"- {s}" for s in _collect_sources(md)))

    parts.append(
        "\nSynthesise the above into the required JSON research note. Be thorough; "
        "this report is read by a professional investor."
    )
    return "\n".join(parts)


def _render_markdown(data: Dict[str, Any], md: Dict[str, Any],
                     briefs: List[Dict[str, str]], ticker: str, company: str) -> str:
    metrics = data.get("key_metrics") or {}
    metric_lines = (
        "\n".join(f"| {k} | {v} |" for k, v in metrics.items())
        if isinstance(metrics, dict) and metrics
        else "| — | No verified metrics available |"
    )
    sources = data.get("sources") or _collect_sources(md)
    source_lines = "\n".join(f"- {s}" for s in sources)
    agent_lines = "\n".join(
        f"- **{b['name']}** — {b['status']}: {b['summary']}" for b in briefs
    )

    return f"""# FinPilot Research Note: {company} ({ticker})

*Generated {md.get('as_of')}*

---

## Investor Mandate
{data.get("investor_profile", "")}

---

## Executive Summary
{data.get("executive_summary", "")}

---

## Key Metrics

| Metric | Value |
| --- | --- |
{metric_lines}

---

## Technical Outlook
{data.get("technical_outlook", "")}

---

## Fundamental View
{data.get("fundamental_view", "")}

---

## Valuation
{data.get("valuation_view", "")}

---

## News & Sentiment
{data.get("news_sentiment", "")}

---

## Risk Assessment
{data.get("risk_assessment", "")}

---

## Scenario Analysis
{data.get("scenario_analysis", "")}

---

## Catalysts To Watch
{data.get("catalysts_to_watch", "")}

---

## Final Verdict
{data.get("final_verdict", "")}

**Confidence:** {data.get("confidence", "Medium")}

---

## Data Availability
{data.get("data_availability", "")}

## Research Pipeline
{agent_lines}

## Sources
{source_lines}

---

*{
    data.get(
        "disclaimer",
        "This report is for informational purposes only "
        "and does not constitute financial advice.",
    )
}*
"""


# ---------------------------------------------------------------------------
# Analysis Endpoint
# ---------------------------------------------------------------------------

@router.post(
    "/analyze",
    response_model=AnalyzeResponse,
    summary="Run a full multi-stage AI research pipeline",
    description=(
        "Resolves the instrument, retrieves verified yfinance market data and "
        "computes indicators, runs five specialist research stages concurrently, "
        "then synthesises a long-form structured investment research report. "
        "This demo path bypasses the LangGraph pipeline entirely."
    ),
    operation_id="demoAnalyzeCompany",
)
async def analyze_company(request: AnalyzeRequest) -> AnalyzeResponse:
    """Run the research pipeline and return a synthesised research note."""

    # --- Stage 0: resolve instrument + collect verified data --------------
    ticker, company, resolution_notes = await asyncio.to_thread(
        _resolve_instrument, request.query, request.ticker, request.target_company
    )
    market_data = await asyncio.to_thread(_fetch_market_data, ticker)
    market_data["ticker"] = ticker

    # --- Stages 1-5: concurrent specialist research -----------------------
    try:
        briefs = await _run_research(request, market_data)
    except HTTPException:
        raise
    except Exception as exc:
        raise HTTPException(
            status_code=status.HTTP_500_INTERNAL_SERVER_ERROR,
            detail=f"Research pipeline failed: {exc}",
        ) from exc

    if all(b["status"] == "failed" for b in briefs):
        raise HTTPException(
            status_code=status.HTTP_502_BAD_GATEWAY,
            detail="All research stages failed; no report could be produced.",
        )

    # --- Stage 6: synthesis on Compound Mini ------------------------------
    synthesis_prompt = _build_synthesis_prompt(
        request, market_data, briefs, resolution_notes
    )

    try:
        raw = await asyncio.to_thread(
            _generate_text,
            synthesis_prompt,
            _ANALYSIS_SYSTEM,
            SYNTHESIS_TOKENS,
            0.35,
            ORCHESTRATOR_MODEL,
        )
    except HTTPException:
        raise
    except Exception as exc:
        raise HTTPException(
            status_code=status.HTTP_500_INTERNAL_SERVER_ERROR,
            detail=f"Groq synthesis call failed: {exc}",
        ) from exc

    cleaned = re.sub(r"```(?:json)?", "", raw).strip().strip("`").strip()
    try:
        data: Dict[str, Any] = json.loads(cleaned)
    except json.JSONDecodeError:
        # Salvage the outermost JSON object if the model added stray prose.
        match = re.search(r"\{.*\}", cleaned, re.DOTALL)
        if not match:
            raise HTTPException(
                status_code=status.HTTP_502_BAD_GATEWAY,
                detail=f"Failed to parse synthesis JSON response. Preview: {raw[:400]}",
            )
        try:
            data = json.loads(match.group(0))
        except json.JSONDecodeError as exc:
            raise HTTPException(
                status_code=status.HTTP_502_BAD_GATEWAY,
                detail=(
                    f"Failed to parse synthesis JSON response: {exc}. "
                    f"Preview: {raw[:400]}"
                ),
            ) from exc

    final_ticker = data.get("ticker") or ticker or "N/A"
    final_company = (
        data.get("company")
        or market_data.get("long_name")
        or company
        or request.target_company
        or "Unknown Company"
    )

    # Agent statuses describe what the pipeline actually did.
    agent_statuses = [
        AgentStatus(name=b["name"], status=b["status"], summary=b["summary"])
        for b in briefs
    ]
    agent_statuses.append(
        AgentStatus(
            name="Synthesis Agent",
            status="completed",
            summary="Specialist briefs reconciled into the final research note.",
        )
    )

    raw_markdown = _render_markdown(
        data, market_data, briefs, final_ticker, final_company
    )

    key_metrics = data.get("key_metrics") or {}
    if not isinstance(key_metrics, dict):
        key_metrics = {}
    key_metrics = {str(k): str(v) for k, v in key_metrics.items()}

    sources = data.get("sources") or _collect_sources(market_data)
    if not isinstance(sources, list):
        sources = [str(sources)]

    return AnalyzeResponse(
        ticker=final_ticker,
        company=final_company,
        executive_summary=data.get("executive_summary", ""),
        technical_outlook=data.get("technical_outlook", ""),
        fundamental_view=data.get("fundamental_view", ""),
        news_sentiment=data.get("news_sentiment", ""),
        risk_assessment=data.get("risk_assessment", ""),
        final_verdict=data.get("final_verdict", ""),
        confidence=data.get("confidence", "Medium"),
        disclaimer=data.get(
            "disclaimer",
            (
                "This report is for informational purposes only "
                "and does not constitute financial advice."
            ),
        ),
        agent_statuses=agent_statuses,
        raw_markdown=raw_markdown,
        investor_profile=data.get("investor_profile", ""),
        valuation_view=data.get("valuation_view", ""),
        scenario_analysis=data.get("scenario_analysis", ""),
        catalysts_to_watch=data.get("catalysts_to_watch", ""),
        data_availability=data.get("data_availability", ""),
        key_metrics=key_metrics,
        sources=[str(s) for s in sources],
        research_briefs={b["name"]: b["brief"] for b in briefs},
    )
