import React, { useState, useEffect } from 'react';
import { useParams, useNavigate } from 'react-router-dom';
import { FileText, Printer } from 'lucide-react';
import { ReportView } from '../components/report/ReportView';
import { mockApi } from '../services/mockApi';
import { useApp } from '../context/AppContext';
import { FinalReport } from '../types';

export const ReportsPage: React.FC = () => {
  const { id } = useParams<{ id: string }>();
  const navigate = useNavigate();
  const { activeReport, setActiveReport } = useApp();

  const [report, setReport] = useState<FinalReport | null>(activeReport);
  const [loading, setLoading] = useState(false);

  const targetReportId = id || activeReport?.report_id || 'rep-aapl-001';

  useEffect(() => {
    let active = true;
    setLoading(true);
    mockApi.getReport(targetReportId).then((data: FinalReport) => {
      if (active) {
        setReport(data);
        setActiveReport(data);
        setLoading(false);
      }
    });
    return () => {
      active = false;
    };
  }, [targetReportId, setActiveReport]);

  const handleSelectOtherReport = (newId: string) => {
    navigate(`/reports/${newId}`);
  };

  if (loading || !report) {
    return (
      <div className="p-16 text-center text-xs text-slate-500">
        Loading investment research report...
      </div>
    );
  }

  return (
    <div data-testid="reports-page" className="space-y-6">
      {/* Top action bar */}
      <div className="flex flex-col sm:flex-row sm:items-center justify-between pb-4 border-b border-slate-200 gap-3">
        <div className="flex items-center space-x-3">
          <div className="w-9 h-9 rounded-lg bg-emerald-600 flex items-center justify-center text-white">
            <FileText className="w-5 h-5" />
          </div>
          <div>
            <h2 className="text-xl font-bold text-slate-900">
              Institutional Investment Report
            </h2>
            <p className="text-xs text-slate-500">
              Complete evidence-grounded research dossier generated by FinPilot
            </p>
          </div>
        </div>

        <div className="flex items-center space-x-2">
          {/* Report switcher if multiple */}
          <select
            value={report.report_id}
            onChange={(e) => handleSelectOtherReport(e.target.value)}
            className="px-3 py-1.5 text-xs bg-white border border-slate-300 rounded-lg text-slate-700 font-semibold focus:outline-none focus:ring-2 focus:ring-emerald-500"
          >
            <option value="rep-aapl-001">Apple Inc. (AAPL)</option>
            <option value="rep-infy-002">Infosys Ltd. (INFY)</option>
          </select>

          <button
            type="button"
            onClick={() => window.print()}
            className="inline-flex items-center px-3 py-1.5 text-xs font-semibold rounded-lg bg-white border border-slate-300 text-slate-700 hover:bg-slate-50 transition-colors shadow-sm"
          >
            <Printer className="w-3.5 h-3.5 mr-1 text-slate-400" />
            Print / Export
          </button>
        </div>
      </div>

      {/* Render complete Report View */}
      <ReportView report={report} />
    </div>
  );
};
