"""Pydantic schemas for Phase 5.1 CIO / Router Agent.

Defines strongly-typed input, output, and task configuration models
for routing financial research requests to specialist agents.
"""

from enum import Enum
from typing import Any, Dict, List, Optional

from pydantic import BaseModel, ConfigDict, Field, field_validator, model_validator

from app.agents.state import (
    CIORoutingDecisionState,
    ClarifiedRequest,
    InvestorProfile,
)


class SpecialistName(str, Enum):
    """Enumeration of specialist analytical agents in FinPilot."""

    TECHNICAL = "technical"
    FUNDAMENTAL = "fundamental"
    NEWS = "news"
    RESEARCH = "research"
    RISK = "risk"


CORE_SPECIALISTS: List[SpecialistName] = [
    SpecialistName.TECHNICAL,
    SpecialistName.FUNDAMENTAL,
    SpecialistName.NEWS,
    SpecialistName.RISK,
]


class SpecialistTask(BaseModel):
    """Configuration and instructions for an individual specialist agent."""

    model_config = ConfigDict(arbitrary_types_allowed=True)

    specialist: SpecialistName = Field(
        ...,
        description="Target specialist agent identifier.",
    )
    task_description: str = Field(
        ...,
        min_length=1,
        description="Focused analytical instructions for the specialist.",
    )
    parameters: Dict[str, Any] = Field(
        default_factory=dict,
        description="Target parameters extracted from state (e.g. ticker).",
    )

    @field_validator("task_description", mode="before")
    @classmethod
    def validate_task_description(cls, v: Any) -> str:
        """Ensure task_description is a non-blank string."""
        if not isinstance(v, str) or not v.strip():
            raise ValueError("task_description cannot be blank.")
        return v.strip()


class CIOInput(BaseModel):
    """Input payload delivered to the CIO / Router Agent."""

    model_config = ConfigDict(arbitrary_types_allowed=True)

    clarified_request: ClarifiedRequest = Field(
        ...,
        description="Clarified user request from upstream agents.",
    )
    investor_profile: InvestorProfile = Field(
        ...,
        description="Validated investor profile with preferences.",
    )
    documents_available: bool = Field(
        default=False,
        description="Whether user documents (10-K, transcripts, PDFs) are available.",
    )


class CIORoutingDecision(BaseModel):
    """Structured routing decision generated by the CIO / Router Agent."""

    model_config = ConfigDict(arbitrary_types_allowed=True)

    target_company: str = Field(
        ...,
        min_length=1,
        description="Target company name or ticker symbol to analyze.",
    )
    ticker: Optional[str] = Field(
        default=None,
        description="Resolved stock ticker symbol, if available.",
    )
    selected_specialists: List[SpecialistName] = Field(
        ...,
        description="List of specialist agents selected for this analysis.",
    )
    specialist_tasks: Dict[SpecialistName, SpecialistTask] = Field(
        default_factory=dict,
        description="Task parameters and instructions keyed by specialist name.",
    )
    reasoning: str = Field(
        ...,
        min_length=1,
        description="Analytical rationale explaining specialist selection.",
    )
    fallback_applied: bool = Field(
        default=False,
        description="True if fallback routing was invoked.",
    )

    @field_validator("target_company", mode="before")
    @classmethod
    def validate_target_company(cls, v: Any) -> str:
        """Ensure target_company is a non-blank string."""
        if not isinstance(v, str) or not v.strip():
            raise ValueError("target_company cannot be blank.")
        return v.strip()

    @field_validator("reasoning", mode="before")
    @classmethod
    def validate_reasoning(cls, v: Any) -> str:
        """Ensure reasoning is a non-blank string."""
        if not isinstance(v, str) or not v.strip():
            raise ValueError("reasoning cannot be blank.")
        return v.strip()

    @field_validator("selected_specialists", mode="before")
    @classmethod
    def validate_and_deduplicate_specialists(cls, v: Any) -> List[SpecialistName]:
        """Validate specialist enum members and eliminate duplicates."""
        if not isinstance(v, list):
            raise ValueError("selected_specialists must be a list.")
        seen = set()
        unique: List[SpecialistName] = []
        for item in v:
            if isinstance(item, SpecialistName):
                val = item
            elif isinstance(item, str):
                cleaned = item.strip().lower()
                try:
                    val = SpecialistName(cleaned)
                except ValueError:
                    raise ValueError(f"'{item}' is not a valid SpecialistName member.")
            else:
                raise ValueError(f"Invalid specialist item: {item}")

            if val not in seen:
                seen.add(val)
                unique.append(val)
        return unique

    @model_validator(mode="after")
    def sync_tasks_with_selected_specialists(self) -> "CIORoutingDecision":
        """Ensure every selected specialist has an associated SpecialistTask."""
        for spec in self.selected_specialists:
            if spec not in self.specialist_tasks:
                self.specialist_tasks[spec] = SpecialistTask(
                    specialist=spec,
                    task_description=f"Analyze {spec.value} for {self.target_company}.",
                    parameters={"company": self.target_company, "ticker": self.ticker},
                )
        return self

    def to_state(self) -> CIORoutingDecisionState:
        """Convert this decision into a GraphState-compatible dictionary."""
        return CIORoutingDecisionState(
            target_company=self.target_company,
            ticker=self.ticker,
            selected_specialists=[s.value for s in self.selected_specialists],
            specialist_tasks={
                (k.value if isinstance(k, SpecialistName) else str(k)): (
                    v.model_dump() if hasattr(v, "model_dump") else dict(v)
                )
                for k, v in self.specialist_tasks.items()
            },
            reasoning=self.reasoning,
            fallback_applied=self.fallback_applied,
        )
