"""Normalized domain and structured output schemas for Fundamental Analyst Agent.

Phase 6.3 defines the input and structured output models for interpreting
deterministic FundamentalMetrics:
- FundamentalAnalystInput: Carries FundamentalMetrics, investor constraints,
  and CIO guidance.
- DimensionAssessment: Structured evaluation per fundamental dimension with
  supporting metrics.
- FundamentalAnalysisOutput: Comprehensive structured fundamental assessment.
"""

from typing import List, Literal, Optional

from pydantic import BaseModel, ConfigDict, Field

from app.models.fundamental_metrics import FundamentalMetrics

DimensionRating = Literal["strong", "moderate", "weak", "neutral", "insufficient_data"]
OverallAssessmentRating = Literal[
    "favorable", "neutral", "unfavorable", "insufficient_data"
]

# Set of all valid deterministic metric attribute names from FundamentalMetrics
VALID_DETERMINISTIC_METRIC_NAMES = {
    # Growth
    "revenue_growth_yoy",
    "net_income_growth_yoy",
    "eps_growth_yoy",
    "revenue_cagr_3yr",
    "earnings_turnaround",
    "earnings_deficit_turnaround",
    "both_periods_deficit",
    "eps_turnaround",
    "eps_deficit_turnaround",
    "both_periods_eps_deficit",
    # Profitability
    "operating_margin",
    "net_profit_margin",
    "roe",
    "roa",
    "negative_equity",
    # Leverage
    "total_debt",
    "total_equity",
    "cash_and_equivalents",
    "net_debt",
    "debt_to_equity",
    "is_net_cash_positive",
    # Cash Flow
    "operating_cash_flow",
    "capital_expenditures",
    "free_cash_flow",
    "fcf_conversion_ratio",
    # Valuation
    "market_cap",
    "pe_ratio",
    "pe_ratio_source",
    "forward_pe",
    "price_to_book",
    "price_to_book_source",
    "dividend_yield",
    "trailing_eps",
    # Context
    "revenue_history",
    "total_revenue",
    "net_income",
    "operating_income",
    "eps",
}


class DimensionAssessment(BaseModel):
    """Evaluation of a specific fundamental dimension with evidence-linked metrics."""

    model_config = ConfigDict(extra="ignore")

    rating: DimensionRating = Field(
        ...,
        description="Qualitative rating for this financial dimension.",
    )
    explanation: str = Field(
        ...,
        description="Concise narrative grounded strictly in the supplied metrics.",
    )
    supporting_metrics: List[str] = Field(
        default_factory=list,
        description=(
            "Names of deterministic metrics supporting this evaluation "
            "(e.g. ['revenue_growth_yoy', 'revenue_cagr_3yr'])."
        ),
    )


class FundamentalAnalystInput(BaseModel):
    """Input payload for the Fundamental Analyst Agent."""

    model_config = ConfigDict(extra="ignore")

    metrics: FundamentalMetrics = Field(
        ...,
        description="Deterministic fundamental metrics computed in Phase 6.2.",
    )
    time_horizon: Optional[str] = Field(
        default=None,
        description="Investor investment time horizon (e.g., '1 year', '5 years').",
    )
    risk_tolerance: Optional[str] = Field(
        default=None,
        description=(
            "Investor risk tolerance "
            "(e.g., 'conservative', 'moderate', 'aggressive')."
        ),
    )
    task_description: Optional[str] = Field(
        default=None,
        description="Specific analytical focus or parameters passed from CIO routing.",
    )


class FundamentalAnalysisOutput(BaseModel):
    """Structured analytical assessment generated by Fundamental Analyst Agent."""

    model_config = ConfigDict(extra="ignore")

    ticker: str = Field(..., description="Normalized uppercase ticker symbol.")
    company_name: Optional[str] = Field(default=None, description="Company name.")
    currency: Optional[str] = Field(
        default=None, description="Reporting currency (e.g. USD)."
    )

    # Core Dimension Assessments (6.3.1)
    financial_health: DimensionAssessment = Field(
        ...,
        description="Overall balance sheet durability, liquidity, and solvency.",
    )
    growth_assessment: DimensionAssessment = Field(
        ...,
        description="Revenue, net income, EPS growth rates and 3-year CAGR trend.",
    )
    profitability_assessment: DimensionAssessment = Field(
        ...,
        description="Operating margin, net profit margin, ROE, and ROA.",
    )
    valuation_assessment: DimensionAssessment = Field(
        ...,
        description=(
            "P/E, forward P/E, P/B, and dividend yield with provenance context."
        ),
    )
    leverage_assessment: DimensionAssessment = Field(
        ...,
        description=("Debt position, net debt, debt-to-equity, and capital structure."),
    )
    cash_flow_assessment: DimensionAssessment = Field(
        ...,
        description=(
            "Operating cash flow, CapEx, free cash flow, and conversion ratio."
        ),
    )

    # Synthesis & Highlights
    key_strengths: List[str] = Field(
        ...,
        min_length=1,
        description="Primary fundamental strengths backed by metrics.",
    )
    key_weaknesses: List[str] = Field(
        ...,
        min_length=1,
        description="Primary fundamental concerns or headwinds backed by metrics.",
    )
    notable_flags: List[str] = Field(
        default_factory=list,
        description=(
            "Explicit event flags (e.g., turnaround to profit, deficit "
            "transition, negative equity)."
        ),
    )
    overall_assessment: OverallAssessmentRating = Field(
        ...,
        description=(
            "Categorical overall fundamental assessment ('favorable', "
            "'neutral', 'unfavorable', 'insufficient_data')."
        ),
    )
    overall_summary: str = Field(
        ...,
        description=(
            "Synthesized narrative conclusion explaining the overall fundamental "
            "assessment."
        ),
    )
    confidence: float = Field(
        ...,
        ge=0.0,
        le=1.0,
        description=(
            "Analytical confidence score reflecting data completeness and "
            "consistency."
        ),
    )
